from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SELECTSUBJECTT(object):

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_cameraA()
        self.ui.setupUi(self.window)
        SELECTSUBJECTT.hide()
        self.window.show()

    def openWindow1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_cameraB()
        self.ui.setupUi(self.window)
        SELECTSUBJECTT.hide()
        self.window.show()

    def openWindow2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_cameraC()
        self.ui.setupUi(self.window)
        SELECTSUBJECTT.hide()
        self.window.show()

    def openWindow3(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_cameraD()
        self.ui.setupUi(self.window)
        SELECTSUBJECTT.hide()
        self.window.show()


    def setupUi(self, SELECTSUBJECTT):
        SELECTSUBJECTT.setObjectName("SELECTSUBJECTT")
        SELECTSUBJECTT.resize(200, 96)

        self.centralwidget = QtWidgets.QWidget(SELECTSUBJECTT)
        self.centralwidget.setObjectName("centralwidget")

        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setText("A")
        self.btn_open.setIconSize(QtCore.QSize(40, 40))
        self.btn_open.setGeometry(QtCore.QRect(10, 25, 40, 40))
        self.btn_open.setObjectName("btn_open")
        self.btn_open.clicked.connect(self.openWindow)

        self.btn_open1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open1.setText("B")
        self.btn_open1.setIconSize(QtCore.QSize(40, 40))
        self.btn_open1.setGeometry(QtCore.QRect(55, 25, 40, 40))
        self.btn_open1.setObjectName("btn_open1")
        self.btn_open1.clicked.connect(self.openWindow1)

        self.btn_open2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open2.setText("C")
        self.btn_open2.setIconSize(QtCore.QSize(40, 40))
        self.btn_open2.setGeometry(QtCore.QRect(100, 25, 40, 40))
        self.btn_open2.setObjectName("btn_open2")
        self.btn_open2.clicked.connect(self.openWindow2)

        self.btn_open3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open3.setText("D")
        self.btn_open3.setIconSize(QtCore.QSize(40, 40))
        self.btn_open3.setGeometry(QtCore.QRect(145, 25, 40, 40))
        self.btn_open3.setObjectName("btn_open3")
        self.btn_open3.clicked.connect(self.openWindow3)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        SELECTSUBJECTT.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SELECTSUBJECTT)
        self.statusbar.setObjectName("statusbar")
        SELECTSUBJECTT.setStatusBar(self.statusbar)


        #def setupUi(self, SELECTSUBJECTT):
    #    SELECTSUBJECTT.setObjectName("SELECTSUBJECTT")
    #    SELECTSUBJECTT.resize(200, 96)
    #    self.horizontalLayoutWidget = QtWidgets.QWidget(SELECTSUBJECTT)
    #   self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 201, 101))
    #   self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
    #   self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
    #   self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
    #   self.horizontalLayout.setObjectName("horizontalLayout")
    #   self.A = QtWidgets.QPushButton(self.horizontalLayoutWidget)
    #   sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    #   sizePolicy.setHorizontalStretch(0)
    #   sizePolicy.setVerticalStretch(0)
    #   sizePolicy.setHeightForWidth(self.A.sizePolicy().hasHeightForWidth())
    #   self.A.setSizePolicy(sizePolicy)
    #   self.A.setMaximumSize(QtCore.QSize(40, 40))
    #   self.A.setText("A")
    #   icon = QtGui.QIcon()
    #   #icon.addPixmap(QtGui.QPixmap("../AppData/Local/Temp/my-icons-collection/png/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    #   self.A.setIcon(icon)
    #   self.A.setIconSize(QtCore.QSize(50, 50))
    #   self.A.setObjectName("A")
    #   self.horizontalLayout.addWidget(self.A)
    #   self.B = QtWidgets.QPushButton(self.horizontalLayoutWidget)
    #   sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    #   sizePolicy.setHorizontalStretch(0)
    #   sizePolicy.setVerticalStretch(0)
    #   sizePolicy.setHeightForWidth(self.B.sizePolicy().hasHeightForWidth())
    #   self.B.setSizePolicy(sizePolicy)
    #   self.B.setMinimumSize(QtCore.QSize(40, 40))
    #   self.B.setMaximumSize(QtCore.QSize(40, 40))
    #   self.B.setText("B")
    #   icon1 = QtGui.QIcon()
    #   icon1.addPixmap(QtGui.QPixmap("../AppData/Local/Temp/my-icons-collection/png/005-photo-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    #   self.B.setIcon(icon1)
    #   self.B.setIconSize(QtCore.QSize(40, 40))
    #   self.B.setObjectName("B")
    #   self.horizontalLayout.addWidget(self.B)
    #   self.C = QtWidgets.QPushButton(self.horizontalLayoutWidget)
    #   sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    #   sizePolicy.setHorizontalStretch(0)
    #   sizePolicy.setVerticalStretch(0)
    #   sizePolicy.setHeightForWidth(self.C.sizePolicy().hasHeightForWidth())
    #   self.C.setSizePolicy(sizePolicy)
    #   self.C.setMinimumSize(QtCore.QSize(40, 40))
    #   self.C.setMaximumSize(QtCore.QSize(40, 40))
    #   self.C.setText("C")
    #   icon2 = QtGui.QIcon()
    #   icon2.addPixmap(QtGui.QPixmap("../AppData/Local/Temp/my-icons-collection/png/004-time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    #   self.C.setIcon(icon2)
    #   self.C.setIconSize(QtCore.QSize(40, 40))
    #   self.C.setObjectName("C")
    #   self.horizontalLayout.addWidget(self.C)
    #   self.D = QtWidgets.QPushButton(self.horizontalLayoutWidget)
    #   sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    #   sizePolicy.setHorizontalStretch(0)
    #   sizePolicy.setVerticalStretch(0)
    #   sizePolicy.setHeightForWidth(self.D.sizePolicy().hasHeightForWidth())
    #   self.D.setSizePolicy(sizePolicy)
    #   self.D.setMinimumSize(QtCore.QSize(40, 40))
    #   self.D.setMaximumSize(QtCore.QSize(40, 40))
    #   self.D.setText("D")
    #   icon3 = QtGui.QIcon()
    #   icon3.addPixmap(QtGui.QPixmap("../AppData/Local/Temp/my-icons-collection/png/003-alarm-clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    #   self.D.setIcon(icon3)
    #   self.D.setIconSize(QtCore.QSize(40, 40))
    #   self.D.setObjectName("D")
    #   self.horizontalLayout.addWidget(self.D)

        #self.retranslateUi(SELECTSUBJECT)
        #self.A.clicked.connect(SELECTSUBJECT.slot_1st)
        #self.B.clicked.connect(SELECTSUBJECT.slot_2nd)
        #self.C.clicked.connect(SELECTSUBJECT.slot_3rd)
        #self.D.clicked.connect(SELECTSUBJECT.slot_4th)
        #QtCore.QMetaObject.connectSlotsByName(SELECTSUBJECT)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SELECTSUBJECTT = QtWidgets.QMainWindow()
    ui = Ui_SELECTSUBJECTT()
    ui.setupUi(SELECTSUBJECTT)
    SELECTSUBJECTT.show()
    sys.exit(app.exec_())